# Generated by Django 6.0.2 on 2026-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualityreading',
            name='light_intensity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
